Error 2022-03-23 10:26:13: Failed to download and store experiments, Class name = b, completed in 244ms, has a falsy return value, Arg 1: <argument cannot be serialized for logging>, Return Value: undefined [Error: Failed with status 404, Not Found, Uri https://raw.githubusercontent.com/microsoft/vscode-python/main/experiments.json
	at H._callback (/root/.vscode/extensions/ms-python.python-2021.1.502429796/out/client/extension.js:59:878755)
	at H.a._callback.a.callback.a.callback (/root/.vscode/extensions/ms-python.python-2021.1.502429796/out/client/node_modules/request.js:187:5437)
	at H.emit (events.js:223:5)
	at H.<anonymous> (/root/.vscode/extensions/ms-python.python-2021.1.502429796/out/client/node_modules/request.js:187:18297)
	at H.emit (events.js:223:5)
	at IncomingMessage.<anonymous> (/root/.vscode/extensions/ms-python.python-2021.1.502429796/out/client/node_modules/request.js:187:17129)
	at Object.onceWrapper (events.js:312:28)
	at IncomingMessage.emit (events.js:228:7)
	at endReadableNT (_stream_readable.js:1185:12)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)]
Error 2022-03-23 10:26:13: Effort to download experiments within timeout failed with error [Error: Failed with status 404, Not Found, Uri https://raw.githubusercontent.com/microsoft/vscode-python/main/experiments.json
	at H._callback (/root/.vscode/extensions/ms-python.python-2021.1.502429796/out/client/extension.js:59:878755)
	at H.a._callback.a.callback.a.callback (/root/.vscode/extensions/ms-python.python-2021.1.502429796/out/client/node_modules/request.js:187:5437)
	at H.emit (events.js:223:5)
	at H.<anonymous> (/root/.vscode/extensions/ms-python.python-2021.1.502429796/out/client/node_modules/request.js:187:18297)
	at H.emit (events.js:223:5)
	at IncomingMessage.<anonymous> (/root/.vscode/extensions/ms-python.python-2021.1.502429796/out/client/node_modules/request.js:187:17129)
	at Object.onceWrapper (events.js:312:28)
	at IncomingMessage.emit (events.js:228:7)
	at endReadableNT (_stream_readable.js:1185:12)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)]
User belongs to experiment group 'AlwaysDisplayTestExplorer - control'
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'AA_testing - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'DeprecatePythonPath - experiment'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
> conda --version
> pyenv root
> python3.7 ~/.vscode/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda info --json
Error 2022-03-23 10:26:14: Failed to download and store experiments, Class name = b, completed in 397ms, has a falsy return value, , Return Value: undefined [Error: Failed with status 404, Not Found, Uri https://raw.githubusercontent.com/microsoft/vscode-python/main/experiments.json
	at H._callback (/root/.vscode/extensions/ms-python.python-2021.1.502429796/out/client/extension.js:59:878755)
	at H.a._callback.a.callback.a.callback (/root/.vscode/extensions/ms-python.python-2021.1.502429796/out/client/node_modules/request.js:187:5437)
	at H.emit (events.js:223:5)
	at H.<anonymous> (/root/.vscode/extensions/ms-python.python-2021.1.502429796/out/client/node_modules/request.js:187:18297)
	at H.emit (events.js:223:5)
	at IncomingMessage.<anonymous> (/root/.vscode/extensions/ms-python.python-2021.1.502429796/out/client/node_modules/request.js:187:17129)
	at Object.onceWrapper (events.js:312:28)
	at IncomingMessage.emit (events.js:228:7)
	at endReadableNT (_stream_readable.js:1185:12)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)]
Error 2022-03-23 10:26:14: Failed to initialize experiments, Class name = b, completed in 398ms, has a falsy return value, , Return Value: undefined [Error: Failed with status 404, Not Found, Uri https://raw.githubusercontent.com/microsoft/vscode-python/main/experiments.json
	at H._callback (/root/.vscode/extensions/ms-python.python-2021.1.502429796/out/client/extension.js:59:878755)
	at H.a._callback.a.callback.a.callback (/root/.vscode/extensions/ms-python.python-2021.1.502429796/out/client/node_modules/request.js:187:5437)
	at H.emit (events.js:223:5)
	at H.<anonymous> (/root/.vscode/extensions/ms-python.python-2021.1.502429796/out/client/node_modules/request.js:187:18297)
	at H.emit (events.js:223:5)
	at IncomingMessage.<anonymous> (/root/.vscode/extensions/ms-python.python-2021.1.502429796/out/client/node_modules/request.js:187:17129)
	at Object.onceWrapper (events.js:312:28)
	at IncomingMessage.emit (events.js:228:7)
	at endReadableNT (_stream_readable.js:1185:12)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)]
> python ~/.vscode/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.1.502429796/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> pyenv root
> pyenv root
Starting Jedi Python language engine.
Error 2022-03-23 10:26:14: Diagnostic Code: InvalidPythonInterpreterDiagnostic, Message: No Python interpreter is selected. You need to select a Python interpreter to enable features such as IntelliSense, linting, and debugging.
Diagnostic Code: InvalidPythonInterpreterDiagnostic, Message: No Python interpreter is selected. You need to select a Python interpreter to enable features such as IntelliSense, linting, and debugging.
